[package]
name = "libzkbob-rs-node"
version = "0.2.2"
authors = ["Dmitry Vdovin <voidxnull@gmail.com>"]
repository = "https://github.com/zkBob/libzkbob-rs/"
license = "MIT OR Apache-2.0"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libzkbob-rs = { path = "../libzkbob-rs", features = ["native"] }
fawkes-crypto = { git = "https://github.com/zkbob/fawkes-crypto", branch = "feature/delegated-deposits", features = ["multicore"] }
neon = { version = "0.10.0", default-features = false, features = ["channel-api", "napi-6", "promise-api", "task-api"] }
# FIXME: Using a random fork for now
neon-serde = { git = "https://github.com/NZXTCorp/neon-serde.git", branch = "refactor/update-neon-0.10" }
serde = "1.0.136"
hex = "0.4.3"

