[package]
name = "libzkbob-rs"
description = "A higher level zkBob API"
version = "1.5.0"
authors = ["Dmitry Vdovin <voidxnull@gmail.com>"]
repository = "https://github.com/zkBob/libzkbob-rs/"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
getrandom = { version = "0.2.3" }
bs58 = "0.4.0"
kvdb = "0.9.0"
kvdb-web = { version = "0.9.0", path = "../libs/kvdb-web", optional = true }
borsh = "0.9.1"
base64 = "0.13.0"
byteorder = "1.4.3"
serde = "1.0.126"
sha3 = "0.10.0"
thiserror = "1.0.26"
kvdb-rocksdb = { version = "0.11.0", optional = true }
kvdb-memorydb = "0.9.0"
hex = { version = "0.4.3", features = ["serde"] }

[dependencies.libzeropool]
git = "https://github.com/zkbob/libzeropool-zkbob"
branch = "master"
package = "libzeropool-zkbob"
version = "1.3.0"
default-features = false
features = ["in3out127"]

[dev-dependencies]
test-case = "1.2.0"
rand = "0.8.4"
serde_json = "1.0.64"

[features]
web = ["getrandom/js", "kvdb-web"]
node = ["getrandom/js"]
native = ["kvdb-rocksdb"]
